### PR TITLE
Add unit tests

### PR DESCRIPTION
**Pull request by bampakoa**
References #34 

Configure karma to include HTML files. Add early tests for the main component

### CODE REVIEW

**Comment by bampakoa** [comment]
@stevermeister I think we are in a good shape right now

**Comment by stevermeister** [comment]
@bampakoa time for release? :)

**Comment by stevermeister** [comment]
is it still WIP?

**Comment by bampakoa** [comment]
Νο

**Comment by stevermeister** [comment]
👍

**Comment by stevermeister** [comment]
ngx-wig@1.0.0 is there! :)

**Pull request merged**
