### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by bampakoa**
Add demo for two-way binding

### CODE REVIEW

**Comment by stevermeister** [comment]
is it only for me? cursor jumps to the beginning on each change

**Comment by stevermeister** [comment]
fixed by changing into ngModel - https://stackblitz.com/edit/ngx-wig-2-way-binding-choit3

**Comment by bampakoa** [comment]
@stevermeister I was about to update the PR but you were quicker than me :smiley: . Please have a look at what I was about to do. What do you think? `pasteHtmlAtCaret` was in ngWig 1 also.

```
public ngOnChanges(changes: SimpleChanges): void {
    if (this.container && changes['content']) {
      // clear the previous content
      this.container.innerHTML = '';

      // add the new content
      this.pasteHtmlAtCaret(changes['content'].currentValue);
    }
  }

  private pasteHtmlAtCaret(html) {
    let sel, range;

    if (window.getSelection) {
      sel = window.getSelection();

      if (sel.getRangeAt && sel.rangeCount) {
        range = sel.getRangeAt(0);
        range.deleteContents();

        // append the content in a temporary div
        let el = document.createElement('div');
        el.innerHTML = html;
        let frag = document.createDocumentFragment(), node, lastNode;
        while ( (node = el.firstChild) ) {
          lastNode = frag.appendChild(node);
        }
        range.insertNode(frag);

        // Preserve the selection
        if (lastNode) {
          range = range.cloneRange();
          range.setStartAfter(lastNode);
          range.collapse(true);
          sel.removeAllRanges();
          sel.addRange(range);
        }
      }
    }
  }
```

**Comment by stevermeister** [comment]
@bampakoa already forgot the usecase for `pasteHtmlAtCaret`, but probably we should really add it :)

**Comment by bampakoa** [comment]
Should I add a new PR?

**Comment by stevermeister** [comment]
yes, please

**Pull request merged**
