### PR TITLE
make possible to filter content that is provided to editor (for example via copy-paste)

### PR DESCRIPTION
**Pull request by stevermeister**
for instance to prevent the situation when extra styles were copy-pasted

### CODE REVIEW

**Comment by bampakoa** [comment]
@stevermeister how about having a separate dropdown option for pasting content as text (no styles), just like MS Word does?

**Comment by stevermeister** [comment]
@bampakoa I believe it's not only Word, it looks like it's already a standard. 
Screenshot 2024-02-20 at 17 24 10





still:
1) this feature is not only about styles, but any filtering/modification
2) for some old-school users it's still a challenge to do a paste and keep the right styles (we have a real use-case for our business application at Studytube)

**Comment by bampakoa** [comment]
Got it! LGTM!

**Comment by stevermeister** [comment]
actually I was asking more not about the feature itself, but more about architectural design. 

I want to always apply the filter:
```
this.pasteHtmlAtCaret(this._filterService.filter(text));
```

(without any if's) and having default as an empty one

but provide a possibility to overwrite in applications that uses ngx-wig

**Comment by stevermeister** [comment]
ok, good, will keep it as it is :)

**Pull request merged**
