### PR TITLE
Build according to Angular Package Format

### PR DESCRIPTION
**Pull request by bampakoa**
- Follow guidelines from [Angular Package Format](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/edit). 
- Support inline templates and stylesheets.

It uses `rollup` under the hood to create a **dist** folder with all available formats of the library.

image

### CODE REVIEW

**Comment by bampakoa** [comment]
@stevermeister I have followed techniques from [this](https://github.com/filipesilva/angular-quickstart-lib) repo of Filipe Silva. I suspect that when they incorporate library generation code in Angular CLI, they will follow this one. But this is just my feeling..

**Comment by stevermeister** [comment]
https://github.com/filipesilva/angular-quickstart-lib
build failed, last src changes 5 months ago - not very promising

**Comment by bampakoa** [comment]
Thanks for the feedback @stevermeister. Do you suggest any alternative way? I have searched through available resources but I have not found a clear solution. CLI folks have it on their roadmap though https://github.com/angular/angular-cli/issues/6510. Maybe we could use the above solution for now and migrate then to Angular CLI way, so that people can upgrade from v1.x ASAP? What are your thoughts?

**Comment by aitboudad** [comment]
why not just using https://github.com/dherges/ng-packagr

**Comment by stevermeister** [comment]
yes, could be. 
also I'm looking at https://github.com/gonzofish/angular-librarian

**Comment by bampakoa** [comment]
@stevermeister What was the outcome, in brief, about packaging libraries in NG-BE? Did you find something interesting?

**Comment by stevermeister** [comment]
currently, there are two most popular package-wizards:
- generator-angular2-library
- ng-packagr

trying them now...

**Comment by stevermeister** [comment]
let's move conversation here - https://github.com/stevermeister/ngx-wig/pull/33

**Pull request closed without merging**
