### PR TITLE
Improve tooling support

### PR DESCRIPTION
**Pull request by bampakoa**
- Fix **Cannot find module 'ngx-wig'.** error in `playground/index.ts` when runnning `tsc` command.
- Fix **Cannot find module 'ngx-wig'.** error in `playground/index.ts` when opening the file in editor.
- Fix **Cannot find module 'ngx-wig'.** error in `playground/index.ts` when running karma.
- Rename the main component of the playground to pass **tslint** kebab case rule.
- Fix unit test for #50

### CODE REVIEW

**Comment by bampakoa** [comment]
@stevermeister the command that fails in TravisCI, passes correctly in my local setup. Do you have any idea?

**Comment by stevermeister** [comment]
'ngx-wig' module problem? different paths local and travis? have no idea

**Comment by bampakoa** [comment]
@stevermeister I think that the check fails because the **dist** folder does not exist in travis.

**Comment by bampakoa** [comment]
@stevermeister sorry, the last commit 1cbfdafb5007458a6ef9d25e1f5076684430f5d8 was not meant to be merged. I pushed it to check if Travis fails. Would you like to revert the merge and commit the PR more clean?

**Comment by stevermeister** [comment]
it's ok while we don't publish it

**Comment by bampakoa** [comment]
Ok, I will remove the obsolete code in another PR :wink:

**Comment by stevermeister** [comment]
yes, please now we found a bug with "disabled" and I want to publish the fix

**Pull request merged**
